package com.shackman.funfacts;

import java.util.Random;

class FactBook {
    Random randomGenerator = new Random();
    // Fields or Member Variables - Properties about the object
    private String[] facts = {
            // original facts
            "Ants stretch when they wake up in the morning.",
            "Ostriches can run faster than horses.",
            "Olympic gold medals are actually made mostly of silver.",
            "You are born with 300 bones; by the time you are an adult you will have 206.",
            "It takes about 8 minutes for light from the Sun to reach Earth.",
            "Some bamboo plants can grow almost a meter in just one day.",
            "The state of Florida is bigger than England.",
            "Some penguins can leap 2-3 meters out of the water.",
            "On average, it takes 66 days to form a new habit.",
            "Mammoths still walked the earth when the Great Pyramid was being built.",
            // Mercury
            "A day on Mercury is 59 Earth days.",
            "A year on Mercury is 88 Earth days.",
            "Mercury is the smallest planet in our Solar System.",
            // Venus
            "A day on Venus is 243 Earth days.",
            "A year on Venus is 225 Earth days.",
            "A day is longer than a year on Venus.",
            "At cloud level, Venus' temperatures are similar to earth's surface temperatures.",
            "Venus has the longest day of any planet in the Solar System.",
            "Venus has more volcanoes than any other planet in the Solar System.",
            "Venus is 1 of 2 planets that rotate in the opposite direction of other planets.",
            "Venus is similar to Earth in size and mass.",
            "Venus is sometimes referred to as Earth's twin or sister.",
            "Venus is the hottest planet in the Solar System.",
            // Earth
            "A day on Earth lasts 24 hours.",
            "A year on Earth last 365 days.",
            "30 Earth sized planets could fit between the Earth and the Moon.",
            "95% of the underwater world is unexplored.",
            "96% of all the Earth's water is contained within the oceans as salt water.",
            "Earth is the 5th largest planet.",
            "Earth is the only planet not named after a god.",
            "Earth is the only planet with water on its surface.",
            "We always see the same side of the moon.",
            // Mars
            "A day on Mars is 24.6 hours.",
            "A year on Mars is 687 Earth days.",
            "Mars has the largest dust storms in the Solar System.",
            "Mars has the largest volcano in the Solar System.",
            "Mars is frequently called the red planet.",
            "Mars is the second smallest planet in the Solar System.",
            // Jupiter
            "A day on Jupiter is 10 hours.",
            "A year on Jupiter is 4333 Earth days.",
            "Jupiter has rings but they are hard to see except when backlit by the sun.",
            "Jupiter has the largest ocean, made of hydrogen instead of water.",
            "Jupiter has the shortest day of any planet in the Solar System.",
            "Jupiter is the largest planet in the Solar System.",
            // Saturn
            "A day on Saturn is 11 hours.",
            "A year on Saturn is 29 Earth years.",
            "Overlooking its large size, Saturn could float on water.",
            "Saturn is the only planet whose average density is less than water.",
            "Saturn's rings are named alphabetically in the order they were discovered.",
            "Saturn's rings are not solid.",
            // Uranus
            "A day on Uranus is 17 hours.",
            "A year on Uranus is 84 Earth years.",
            "Although it's not the coldest planet on average, Uranus reaches the coldest temperatures.",
            "Uranus is 1 of 2 planets that rotate in the opposite direction of other planets.",
            "Uranus is the third largest planet.",
            "Uranus was the first planet located with a telescope.",
            "Uranus' axis is rotated tilted, its north and south poles are near the equator.",
            // Neptune
            "A day on Neptune is 16 hours.",
            "A year on Neptune is 165 Earth years.",
            "Neptune has the strongest winds in the Solar System.",
            "Neptune is the coldest planet in the solar system on average.",
            "Neptune is the only planet not visible to the naked eye.",
            "Sometimes Neptune is farther from the Sun than Pluto.",
            "Winds on Neptune can reach 1300 miles per hour.",
            // Space
            "11 of the 12 men who walked on the moon were boy scouts.",
            "A blue moon is a second full moon in a month.",
            "American Astronauts can vote from space.",
            "Astronauts from Russia are called cosmonauts.",
            "Astronauts from the first few moon missions were quarantined upon their return.",
            "Astronauts must learn Russian.",
            "Black holes don't live forever, they evaporate over time.",
            "It takes our Solar System 240 million years to complete an orbit of the Milky Way.",
            "John Glenn became the oldest person to fly in space in 1998.",
            "John Glenn was the first American to orbit Earth.",
            "Mercury and Venus are the only planets in the solar system without moons.",
            "No country can own the Moon.",
            "Outer space begins at 62 miles above sea level.",
            "The crew of Apollo 7 won an Emmy Award.",
            "The first feline in space, was a cat named Felicette in 1963.",
            "The German V-2 rocket was the first man-made object to travel into space.",
            "The International Space Station is the size of a football field.",
            "The Milky Way will eventually crash into the Andromeda galaxy.",
            "The moon is larger than Pluto.",
            "The sun accounts for 99.86% of the solar system's mass.",
            "The sun is about 4.6 billion years old.",
            "The sun weighs 333,000 times more than Earth.",
            // Birds
            "Cranes are the tallest flying birds.",
            "Sandhill cranes are the most common of all cranes.",
            "There is an all-black chicken; including meat, bones, organs, feathers and beak.",
            "Andean condors are the largest flying bird by combined height and wingspan.",
            "A group of crows is called a murder.",
            "Call ducks are the world's smallest domestic duck breed.",
            "Female ducks are called ducks or hens.",
            "Male ducks are called drakes.",
            "Male mandarin ducks are colorful unlike females who are gray.",
            "Bald eagles can dive at up to 100 miles per hour to catch fish.",
            "Bald eagles have a wingspan of 8 feet.",
            "Eagles can see ultraviolet light.",
            "Eagles have sharper vision and a wider field of vision than humans.",
            "Emus are the only bird with calf muscles.",
            "Peregrine falcons are the fastest animal.",
            "Peregrine falcons can reach speeds of 200 miles per hour when diving.",
            "Flamingos turn pink due to their diet.",
            "The feathers under a flamingos wings are black and can only be seen when flying.",
            "The greater flamingo can be as tall as 4 to 5 feet, and weigh up to 8 pounds.",
            "There are 6 species of flamingos.",
            "Great blue herons have been known to choke by trying to swallow fish too large for their necks.",
            "Great blue herons hunt alone but live in colonies.",
            "The great blue heron is the largest heron in North America.",
            "Bee hummingbirds lay two eggs, the size of coffee beans.",
            "Most hummingbirds weigh less than a nickel.",
            "The bee humming bird is the world's smallest bird.",
            "An ostrich's kick can kill a human or lion.",
            "An ostrich's eye is bigger than its brain.",
            "Ostriches are the largest living bird.",
            "Ostriches blink once a minute.",
            "Ostriches have the largest eyes of any land animal.",
            "Ostriches have the running speed of any bird on land.",
            "Two-toed ostriches are the only birds to have two toes.",
            "A group of owls is called a parliament.",
            "Elf owls are the lightest owl in the world.",
            "Elf owls are the smallest in the world.",
            "Elf owls live in cacti.",
            "Great horned owls can swim.",
            "Owls are farsighted.",
            "Owls cannot move their eyes.",
            "Owls don't usually hunt in the rain.",
            "Owls have 14 neck bones, humans have 7.",
            "Owls live in nests built by other bird.",
            "Owls make no noise when flying.",
            "Snowy owls are active during the day and night.",
            "Snowy owls are the heaviest owls in North America.",
            "Some owls can detect prey under up to 18 inches of snow using sound.",
            "Male peafowls are referred to as peacocks.",
            "Female peafowls are referred to as peahens.",
            "A pelican's pouch is called a gular.",
            "Brown pelicans dive for food.",
            "Pelicans' have 9 foot wingspans.",
            "Pelicans' throat pouch holds more than its stomach.",
            "White pelicans feed while afloat.",
            "Emperor penguins are the tallest and heaviest penguins.",
            "Female emperor penguins sometimes kidnap unrelated chicks.",
            "Little blue penguins are also known fairy penguins.",
            "Little blue penguins are the smallest penguin.",
            "Only one species of penguin lives north of the equator.",
            "Penguins have a gland behind their eyes that filters out seawater from their blood stream.",
            "Penguins lose all their feathers at once, they stay on land as their new feathers grow.",
            "The colors on a penguin are used for camouflage.",
            "The fastest penguin species can reach speeds of 22 miles per hour.",
            "Baby puffins are called pufflings.",
            "Puffins can reach speeds of 55 miles per hour.",
            "Ravens can learn to talk better than parrots.",
            "Roadrunners are omnivores.",
            "Roadrunners are a type of cuckoo bird.",
            "Roadrunners eat rattlesnakes.",
            "Secretary birds hunt on the ground, although they can fly.",
            "The secretary bird is the only bird that stomps its prey to death.",
            "The toro toucan's bill is a third of the bird's length.",
            "Toucans are found in the wild only in the Americas.",
            "By rotating their heads, turkeys have a 360 degree field of vision.",
            "Female turkeys do not gobble.",
            "Turkeys can run at speeds of 25 miles per hour.",
            "Wild turkeys are able to fly at speeds of up to 55 miles per hour.",
            "Wild turkeys sleep in trees.",
            "Wandering albatross have the largest wingspan of any living bird at almost 12 feet.",
            "The downy woodpecker is the smallest woodpecker in North America and most widespread.",
            // Amphibians
            "Female poison dart frogs lay eggs for their tadpoles to eat.",
            "Most poison dart frogs aren't toxic.",
            "The goliath frog is the largest frog at almost a foot and weight more than 7 pounds.",
            "The world's smallest frog is as small as a cheerio.",
            "Toxic poison dart frogs have neon colors to warn predators.",
            "Wallace's flying frog trees can glide 50 or more feet.",
            "Easter tiger salamanders live in burrows up to 2 feet below the surface.",
            "Oriental fire-bellied toads have triangular pupils.",
            // Insects
            "Dung Beetles use the Milky Way to navigate.",
            "Butterflies taste with their feet.",
            "Monarch butterflies lay their eggs in milkweed.",
            "Crickets have ears on their front legs.",
            "Crickets were named for the sound they make.",
            "The sound crickets make comes from their wings.",
            "The devil worm is the deepest living animal ever found.",
            "Mantises are among the insects most commonly kept as pets.",
            "Praying mantis can swivel their heads 180 degrees.",
            "Scorpions glow neon blue when illuminated by black light.",
            "There are almost 2000 scorpion species.",
            "Snails can sleep up to 3 years.",
            "Jumping spiders can see more colors than humans.",
            "Most spiders have 8 eyes.",
            "Not all spiders build webs, but they do produce silk.",
            "Spiders eat their own webs to get back energy.",
            "Spiders have blue blood.",
            "The Goliath birdeater has hairs on its legs that it can throw like missiles.",
            "The Goliath birdeater is the largest spider on the planet.",
            "There are more than 45,000 known species of spiders.",
            "Wolf spiders can drop a leg when threatened.",
            "Wolf spiders have three microscopic claws at the ends.",
            "Zyzzyva is the last insect in the dictionary, it is a tropical weevil.",
            // Reptiles
            "Chameleons can move their eyes in two separate directions at the same time.",
            "Crocodiles cannot stick their tongues out.",
            "Geckos can clean their eyes with their tongues.",
            "Marine iguanas are only found on the Galapagos Islands.",
            "Komodo dragons can run up to 11 miles an hour.",
            "Komodo dragons have venom glands.",
            "The Komodo dragon is the largest living species of lizard.",
            "The common basilisk lizard can run on the surface of water.",
            "The viviparous or common lizard is the only land reptile native to Ireland.",
            "Sea turtles can't pull their head and limbs inside their shells.",
            "Boa constrictor squeeze their victims until they suffocate.",
            "Burmese pythons can stay underwater for up to 30 minutes.",
            "King cobras are the longest venomous snake.",
            "King cobras are the only snakes that build nests and guard their eggs.",
            "King cobras can reach 18 feet in length.",
            "The green anaconda is the heaviest snake.",
            "There are about 3600 snake species recognized.",
            // Mammals
            "Apes do not have tails.",
            "Gorilla leaders organize activities.",
            "Gorillas usually live on the ground in communities.",
            "Orangutan travel by swinging from branches.",
            "All but one variety of armadillo live in Latin America.",
            "Armadillos are the only mammals that have protective armor.",
            "Armadillo is a Spanish word meaning 'little armored one'.",
            "Giant armadillos sleep about 18 hours a day.",
            "Not all armadillos can encase themselves in their shells.",
            "A group of bats is called a colony.",
            "Bats are the only mammal that can fly.",
            "Female bats give birth upside down.",
            "There are more than 1100 species of bats.",
            "A bear fought in the Polish Army in World War 2.",
            "A group of bears is called a sloth.",
            "Bamboo makes up over 99% of a panda's diet.",
            "Black bears can  be blue-gray, blue-black, brown, cinnamon, or sometimes white.",
            "Brown bears can be as tall as 10 feet.",
            "Brown bears can run at speeds up to 30 miles per hour.",
            "Female bears are called sows.",
            "Grizzly bears can lose 150 pounds over winter.",
            "Male bears are called boars.",
            "Mother sun bears sometimes carry their cubs in their arms.",
            "New born pandas are about the size of a stick of butter.",
            "Pandas do not hibernate.",
            "Polar bears are the largest land predators on earth.",
            "Polar bear fur is transparent, it appears white because it reflects light.",
            "Polar bears have nonretractable claws.",
            "Polar bears have black skin underneath their fur.",
            "Sloth bears carry their young on their back.",
            "Spectacled bears are the only wild bear in South America.",
            "Sun bears are nocturnal.",
            "Sun bears are the smallest member of the bear family.",
            "Sun bears can walk on their hind legs.",
            "There are 8 species of bear.",
            "There are no polar bears in Antarctica, they live in the Arctic.",
            "There is a brown species of panda that feature light and dark brown fur.",
            "A beefalo is part bison, part cow.",
            "Bulls are color blind to red.",
            "Bongos are the largest forest antelope.",
            "Bongos eat burned wood after lightning storms.",
            "Both male and female bongo have horns.",
            "Camels have a 3rd eyelid.",
            "A group of grown cats is called a clowder.",
            "Cats have 32 muscles in each ear.",
            "Cats have 244 bones in their bodies.",
            "Cats usually have fewer toes on their back paws than front paws.",
            "Cheetahs are the fastest animal on land.",
            "Cheetahs are the only big cats that can’t roar.",
            "Cheetahs can reach 60 miles per hour in 3 seconds.",
            "A coydog is a mix between a dog and a coyote.",
            "Coyotes are faster than roadrunners.",
            "Chihuahua is the smallest breed of dog.",
            "Dalmatians spots appear 3 to 4 weeks after birth.",
            "A group of dolphins is called a school or pod.",
            "A wholphin is a mix between bottlenose dolphin and a false killer whale.",
            "Dolphins can rest half their brain and keep the other half conscious.",
            "Female dolphins are called cows.",
            "Male dolphins are called bulls.",
            "There are more than 40 species of dolphins.",
            "There are pinkish albino bottlenose dolphins.",
            "Young dolphins are called calves.",
            "African elephants are the largest land animal.",
            "Elephants are unable to jump.",
            "Elephant brains can weigh as much as 11 pounds,",
            "Elephants can recognize themselves.",
            "Elephants don't like peanuts.",
            "Elephant trunks contain about 100,000 muscles.",
            "A female ferret is called a jill.",
            "A group of ferrets is called a business.",
            "A male ferret is called a hob.",
            "Ferrets under one year old are known as kits.",
            "A group of foxes is called a skulk or leash.",
            "Arctic foxes can survive in temperatures as low as -58 degrees Fahrenheit.",
            "Fennec foxes are mostly found in the Sahara and North Africa.",
            "Fennec foxes are the smallest foxes in the world.",
            "Foxes live in small family groups.",
            "Red foxes are the most common fox.",
            "Giant elands are the largest species of antelope.",
            "The giant otter is the longest member of the weasel family.",
            "A giraffe's heart weighs about 25 pounds.",
            "A giraffe's tongue can be around 20 inches long.",
            "A group of giraffes is called a tower.",
            "Giraffe spots are unique.",
            "Giraffes are the tallest mammal in the world.",
            "Giraffes can run as fast as 35 miles per hour.",
            "The legs of a giraffe are taller than most humans.",
            "Goats have rectangular pupils.",
            "Mountain goats are more closely related to antelopes.",
            "Horses can only breath through their nose.",
            "Horses can sleep while standing or laying down.",
            "Horses have the largest eyes of any land mammal.",
            "There are 8 horse blood types.",
            "Charley Horses are muscle spasms.",
            "Every human has a unique tongue print.",
            "Humans can distinguish about 10 million different colors.",
            "Noses and ears continue to grow as humans age.",
            "Some people never develop fingerprints.",
            "Sneezing cannot occur while sleeping.",
            "The human heart is in the middle of the body, not the left side.",
            "The liver is the only internal organ that can regenerate itself.",
            "The right lung is larger than the left lung.",
            "Toothpaste suppresses your taste buds that perceive sweetness.",
            "Your brain keeps developing until your late 40s.",
            "Your stomach growling is called borborygmus.",
            "Females lead spotted hyena groups.",
            "Hyenas are closely more related to cats than dogs.",
            "Spotted hyenas live in groups called clans which can contain up to 80 individuals.",
            "Running impalas jump over anything in their path.",
            "A panther is not a real animal.",
            "Jaguars are the largest big cat in South America.",
            "The spots on Jaguars are called rosettes.",
            "A gray kangaroo can hop at more than 35 miles per hour.",
            "A group of kangaroos is called a mob.",
            "Female red kangaroos have a blue-hued coat, sometimes they are called blue fliers.",
            "Most kangaroos are left handed.",
            "The red kangaroo is the largest marsupial.",
            "A koala's brain makes up 0.2% of its body weight.",
            "Koala bears aren't bears.",
            "Koala twins are very rare.",
            "Koalas have fingerprints similar to humans.",
            "Koalas sleep up to 20 hours a day.",
            "Koalas store leaves in pouches in their cheeks.",
            "Lemurs are found only on the island of Madagascar and small neighboring island.",
            "Llamas and Alpacas exist only as domesticated animals.",
            "A group of lines is a pride.",
            "A group of male lions is called a coalition.",
            "A lion's roar can be heard up to 5 miles away.",
            "Leopon is a mix of leopard and lion.",
            "Lions are the only cats that live in groups.",
            "Lions are the only cats with manes.",
            "Manatees are born underwater and must be helped by their mothers to get to the surface.",
            "Manatees are related to elephants.",
            "Manatees can remain underwater for 15 minutes when not swimming.",
            "Manatees never leave the water.",
            "A meerkat can spot an eagle in flight more than 1000 feet away.",
            "Narwhals spiral tusks can reach almost 9 feet long.",
            "Opossums are known as possums in North America.",
            "Opossums are the largest marsupials in the Western Hemisphere.",
            "Opossums don't play dead, they pass out from overexcitement.",
            "Opossums have 50 teeth.",
            "Pangolin's tongues are longer than their bodies.",
            "Birds sometimes ride on warthogs feeding on tiny creatures.",
            "European wild boars wash dirty food before eating.",
            "Male platypus are toxic.",
            "Platypus are one of few species of mammals that lay eggs.",
            "Platypus can stay submerged in water for only a few minutes.",
            "Platypus don't have stomachs.",
            "Platypus have retractable webbing.",
            "Platypus use their bill to detect electrical signals.",
            "The closest living relative to pronghorns are giraffes.",
            "The pronghorn is not a type of antelope.",
            "The pronghorn is the second fastest land mammal in the world.",
            "Rabbits often sleep with their eye open.",
            "Most male and female reindeer grow antlers.",
            "Reindeer are often known as Caribou.",
            "Reindeer eyes are gold in the summer, and blue in the winter.",
            "The eyes of reindeer change color through the seasons.",
            "Sea otters hold hands when sleeping to keep from drifting apart.",
            "Three toed sloths and manatees have more neck bones than giraffes.",
            "Snow Leopards live the mountains of Central Asia.",
            "Tapirs are related to horses and rhinoceroses.",
            "A tiger's roar can be heard up to 2 miles away.",
            "In the 19th century, one tiger killed over 430 people.",
            "No two tigers have the same stripe pattern.",
            "Siberian tigers are the largest cat in the wild.",
            "The night vision of a tiger is six times better than humans.",
            "There are no wild tigers in Africa.",
            "Tigers also have striped skin, not just fur.",
            "Tigers are a bear predator.",
            "Tigers that mate with lions give birth to tigons and ligers.",
            "White tigers are not albino.",
            "Only Native Americans are currently allowed to hunt walruses.",
            "The hairs in a walrus mustache are as sensitive as fingers.",
            "Tusks help walruses climb out of the sea.",
            "Baby blue whales gain about 200 pounds per day in their first year.",
            "Blue whales are the largest animal known to have existed.",
            "Blue whales live on average 80-90 years.",
            "Killer whales are part of the dolphin family.",
            "Some whales are known to prey on animals such as deer and moose as they swim.",
            "There is only one known albino humpback whale.",
            "Whale's tongues can weigh as much as an elephant.",
            "A wolf pack is two or more wolves that have a defined territory.",
            "Wolves are the largest members of the dog family.",
            "A group of zebras is a called a herd, dazzle, or zeal.",
            "Zebras are black with white stripes.",
            "Zebra stripes are unique to each zebra.",
            // Rodents
            "Beavers are known for building dams, canals and lodges.",
            "Beavers are the second largest rodent in the world.",
            "Beavers have transparent eyelids like goggles.",
            "There are 2 species of beaver.",
            "Capybaras are the largest rodent in the world.",
            "Grasshopper mice are immune to various venom.",
            "Grasshopper mice eat snakes.",
            "Groundhogs are also known as woodchucks or whistlepigs.",
            "Groundhogs are the largest member of the squirrel family.",
            "Young groundhogs may be called chucklings.",
            "A single porcupine may have 30,000 or more quills.",
            "Porcupines cannot shoot their quills.",
            "The North American porcupine is the largest of all porcupines.",
            "There are 29 species of porcupine worldwide.",
            "Flying squirrels can glide up to 300 feet.",
            "Squirrels are one of the few animals that can climb vertically down head-first.",
            "Squirrels are organized sometimes organizing nuts by differing characteristics.",
            "Squirrels climb down trees head first by rotating their back ankles 180 degrees.",
            // Sealife
            "A sardine is not a specific species of fish, but applies to many small varieties of fish.",
            "All fish live in water and have a backbone.",
            "Some fish can swim backwards.",
            "Anglerfish's glow comes from bacteria that live in its lure.",
            "Male and female anglerfish fuse together.",
            "Chinese sturgeon can reach up to 16 feet and 1100 pounds.",
            "Chinese sturgeon have mouths under their jaws.",
            "All clownish are born male.",
            "Goldfish can be taught tricks.",
            "There are over 100 variety of goldfish.",
            "There is a species of jellyfish that never dies.",
            "Mekong Giant Catfish are the largest scaleless freshwater fish.",
            "Mekong Giant Catfish can weigh up to 650 pounds and reach 10 feet.",
            "Dumbo octopuses can change color and size.",
            "Dumbo octopuses do not use ink.",
            "Octopus have 3 hearts.",
            "Octopus have blue blood.",
            "Octopus' skin can sense light.",
            "The blue-ringed octopus is the only one deadly to humans.",
            "The mimic octopus can change its color and change its shape to look like other toxic fish.",
            "There are around 300 species of octopus.",
            "Peacock mantis shrimp can punch at 50 miles per hour.",
            "There are more than 120 species of pufferfish.",
            "There is enough toxin in a pufferfish to kill 30 humans.",
            "There is no known antidote for pufferfish poison.",
            "Female sharks have thicker skin than males.",
            "Sharks can replace teeth in as short as 8 days.",
            "Sharks do not blink.",
            "Sharks have an inner ear.",
            "The longfin mako is the second-biggest lamnidae shark.",
            "The shortfin mako can reach speeds of at least 31 miles per hour.",
            "The shortfin mako is on record as the fastest-swimming shark.",
            "There are 2 species of mako shark.",
            "Whale shark are the largest non-mammal fish.",
            "Whale shark can be as large as 40 feet and weigh several tons.",
            "A shrimp's heart is in its head.",
            "A giant squid's eye can be as large as a beach ball.",
            "Starfish can't see colors.",
            "Starfish contain filtered seawater instead of blood.",
            "Starfish do not have brains.",
            "There are species of starfish with 10, 20 or 40 arms.",
            // Candy / Snacks
            "A dentist helped create cotton candy.",
            "A janitor invented Flamin Hot Cheetos.",
            "Animal crackers were created in England.",
            "All of the meeting rooms at Ben & Jerry's HQ are named after ice cream flavors.",
            "Barbeque flavored chips were the first flavored chip in the U.S.",
            "Ben & Jerry's was originally going to be a bagel company.",
            "Chocolate melts just below the human body temperature.",
            "German chocolate cake isn't German, it's named after an American baker.",
            "Haribo's green gummy bear is strawberry.",
            "Junior Mints are named after the founder's favorite broadway play, Junior Miss.",
            "Kit Kats are produced by Nestle globally, and by Hershey in the U.S.",
            "Oreo's have a cookie to cream ratio of 71% to 29%.",
            "Pez's name comes from German word for peppermint, pfefferminz.",
            "Potato chip bags are filled with nitrogen gas.",
            "Reese's Pieces aren't made with the same filling as Reese's Peanut Butter Cups.",
            "Snickers bar is named after a horse.",
            "Skittles were made by a British company in 1974.",
            "Starburst were originally called Opal Fruits.",
            "The chocolate chip cookie was created in Massachusetts.",
            "The cow on packages of Ben & Jerry is named Woody.",
            "The filling in Kit Kats is made from damaged Kit Kats.",
            "The inventor of peanut M&Ms was allergic to peanuts.",
            "The man on the Pringles can is named Julius.",
            "The Oreo was launched as an imitation of the Hydrox cookie.",
            "Vanilla was the first flavor created by Ben & Jerry's.",
            "White chocolate doesn't contain chocolate solids, only cocoa butter.",
            // Food and Drink
            "All froot loops are the same flavor.",
            "An egg was the second food intentionally microwaved and it exploded.",
            "Applesauce was the first food eaten in space.",
            "Bacon was the first food eaten on the moon.",
            "Banana ketchup is popular in the Philippines.",
            "Burger King is called Hungry Jack's in Australia.",
            "Coca-Cola bottles were shaped like a cocoa bean.",
            "Coca-Cola cans were invented to be shipped to armed forces overseas.",
            "Dr Pepper was created in Texas.",
            "Fanta originated in Germany.",
            "French Toast wasn't created in France.",
            "Fried spider is a delicacy in Cambodia.",
            "Fugu is the name of pufferfish dish in Japan.",
            "Hawaiian pizza was created in Canada.",
            "Honey never spoils.",
            "Kool-Aid came from a drink called Fruit Smack.",
            "Kool-Aid was invented in Nebraska.",
            "McDonald's once made bubble-gum flavored broccoli.",
            "McDonald's used to own Chipotle.",
            "Milk chocolate was invented in Switzerland.",
            "Milkshakes were originally alcoholic.",
            "Mountain Dew was created in Tennessee.",
            "Pizza Hut delivered a pizza to the International Space Station in in 2001.",
            "Popcorn was the first food cooked intentionally in a microwave.",
            "Ronald McDonald is called Donald McDonald in Japan.",
            "The first chocolate bar was made in England.",
            "The food spam gets its name from combining spiced ham.",
            "The shape of a pringle is called Hyperbolic Paraboloid.",
            "There is beer brewed from bananas in Africa.",
            "Tiramisu means pick me up in Italian.",
            "Trix originally had 3 flavors, raspberry red, lemony yellow, orangey orange.",
            "Wrigley's Juicy Fruit gum was the first item to be scanned by bar code.",
            // Fruits
            "Fruit salad trees bear several different fruit.",
            "Pomology is the study of fruits.",
            "The stickers on fruit are edible.",
            "Almonds are part of the rose family.",
            "Apples are part of the rose family.",
            "Apricots are part of the rose family.",
            "Avocados are berries.",
            "A banana bunch consists of groups of banana hands.",
            "A group of banana fingers is called a hand.",
            "Bananas are berries.",
            "Bananas are curved because they grow against gravity.",
            "Ripening bananas glow blue under blacklight.",
            "Single bananas are also called fingers.",
            "The strings on a banana that come off when you peel it are called Phloem bundles.",
            "Bell peppers are fruit.",
            "Bell peppers come in colors red, yellow, orange, green, white and purple.",
            "Cherries are part of the rose family.",
            "There are more than 1000 different varieties of sweet cherries.",
            "Cucumbers are fruit.",
            "Cucumbers consist of 96% water.",
            "Durians are banned in certain southeast asia places due to their smell.",
            "Eggplant is a berry.",
            "Kiwis are berries.",
            "Lemons have more sugar than strawberries.",
            "In warm countries near the equator, oranges stay green.",
            "When oranges are exposed to cold they change from green to orange.",
            "Peaches are part of the rose family.",
            "Peaches were the first fruit eaten on the moon.",
            "Pears are part of the rose family.",
            "Pineapple is a berry.",
            "Plums are part of the rose family.",
            "Pomegranates can contain between 200 and 1400 seeds.",
            "Pumpkins are fruit.",
            "Raspberries is part of the rose family.",
            "Raspberries is not a berry.",
            "Strawberries are not berries.",
            "Strawberries are part of the rose family.",
            "Strawberries have on average 200 seeds.",
            "Strawberries have more vitamin C than oranges.",
            "All parts of a watermelon are edible.",
            "Watermelons are 92% water.",
            "Watermelon is a berry.",
            // Vegetables
            "Asparagus consists of 93% water.",
            "Broccoli is a man-made vegetable.",
            "Cauliflower comes in colors such as white, green, orange and purple.",
            "The potato was the first vegetable grown in space.",
            "Yams and Sweet potatoes are not the same.",
            // Geography
            "Billboards are prohibited in Vermont, Alaska, Hawaii and Maine.",
            "Colorado, Wyoming, and Utah are the only states that have their borders defined by straight lines.",
            "Every continent has a city named Rome.",
            "Four Corners Monument is the only point shared by four states.",
            "Hawaii and Alaska have never surpassed 100 degrees Fahrenheit.",
            "Hells Canyon in Oregon, Idaho and Washington is North America's deepest river gorge.",
            "In 2018 Texas, California and New York have economies bigger than Russia.",
            "Mount Everest is Earth's highest mountain above sea level.",
            "Q is the only letter not in the name of a U.S. state.",
            "There are 2 U.S. capitals that have the state in their name.",
            "There are 3 countries entirely inside of another country.",
            "Tornio Golf Club has holes in 2 countries, Finland and Sweden.",
            "Yellowstone Park is larger than Rhode Island and Delaware combined.",
            "Yellowstone Park sits above the largest supervolcano in North America.",
            "Yellowstone Park was the first national park in the U.S.",
            "Alabama hosted the first national Veterans Day celebration.",
            "Alabama was the first state to declare Christmas a legal holiday.",
            "There is historic building in Alabama known as Sweet Home, Alabama.",
            "There is post office that delivers mail by boat in Alabama.",
            "19 states could fit in Alaska.",
            "75 New Jerseys could fit in Alaska.",
            "Alaska has a sand desert.",
            "Alaska is the most eastern and western state.",
            "Alaska is the only state that can be typed on one row of a standard keyboard.",
            "Alaska's coastline is longer than all other states combined.",
            "Due to summer sun being as much as 20 hours, produce can grow large in Alaska.",
            "The largest county in Alaska is roughly the same size as Germany.",
            "The U.S. purchased Alaska from Russia.",
            "The largest diamond ever found came from Arkansas.",
            "Alcatraz was the first lighthouse on the west coast of the U.S.",
            "California has the highest and lowest point in the U.S.",
            "San Jose was the original capital of California.",
            "The California grizzly bear is extinct.",
            "The Golden Gate Bridge's color is called International Orange.",
            "The tallest tree in the world is in California.",
            "Colorado is nicknamed the centennial state because it became a state 100 years of America's Independence.",
            "Colorado is the only state that is above 1000 meters elevation.",
            "Delaware has the lowest number of counties.",
            "Delaware has the lowest average elevation of all states.",
            "Delaware was named after the Delaware River.",
            "Delaware was the first state.",
            "The Smithsonian is named after James Smithson.",
            "The Washington Monument is 2 different colors.",
            "The White House was designed by an Irish architect.",
            "Florida has the second most number of islands of any state.",
            "Florida is the flattest state.",
            "Florida is the only place where alligators and crocodiles coexist.",
            "Florida is the only state that borders both the Atlantic Ocean and the Gulf of Mexico.",
            "There is no place in Florida that is more than 60 miles from a body of salt water.",
            "The Girl Scouts were founded in Georgia.",
            "Hawaii consists of 8 main islands.",
            "Hawaii is the only composed entirely of islands.",
            "Hawaii is the only state located in Oceania.",
            "Hawaii is the only state located outside of North America.",
            "There are 13 letters in the Hawaiian alphabet.",
            "Though mostly underwater, Mount Kea in Hawaii is the tallest mountain in the world.",
            "The Harlem Globetrotters originated in Chicago.",
            "The first gasoline pump was invented and sold in Fort Wayne, Indiana.",
            "Iowa is the only state whose east and west borders are formed entirely by rivers.",
            "Kentucky is the only U.S. state to have a continuous border of rivers running along three sides.",
            "Kentucky used to be part of Virginia.",
            "Louisiana doesn't have counties, they are called parishes.",
            "Maine has a 40 acre desert.",
            "Maine is the only one syllable state.",
            "Maine is the only state that borders just one other state.",
            "Maine is the U.S. state closest to Africa.",
            "The official state sport of Maryland is jousting.",
            "The Ouija board was created in Maryland.",
            "Boston established the first subway system in the U.S.",
            "Boston Latin School is the oldest public school.",
            "Harvard is the U.S.'s oldest institution of higher learning.",
            "The first telephone call took place in Boston.",
            "The Massachusetts constitution is the oldest constitution still in effect.",
            "The oldest public park in the U.S. is the Boston Common.",
            "Michigan is the only state to consist of two peninsulas.",
            "8 different states border Missouri.",
            "Missouri is known as the cave state.",
            "St. Louis held the first Olympics in the United States.",
            "Boulder City is one of only two places in Nevada that prohibits gambling.",
            "Boulder City was constructed for people working on the Hoover Dam.",
            "Las Vegas city facilities run on renewable energy.",
            "Nevada is the driest state in the U.S.",
            "New Hampshire delegates were first to vote for Declaration of Independence.",
            "New Jersey is one of two states where motorist aren't allowed to pump their gas.",
            "The first college football game was played in New Jersey.",
            "There is a non-active volcano in New Jersey.",
            "New Mexico is not named after Mexico.",
            "Santa Fe is the highest state capital in the U.S.",
            "The road runner is the state bird of New Mexico.",
            "A woman survived an elevator falling 75 floors in the Empire State Building.",
            "Before Brooklyn became part of NYC it was the 4th most populated city.",
            "Brooklyn became part of New York City in 1898.",
            "New York City was the first national capital.",
            "New York City was the national capital for only one year.",
            "Niagara Falls State Park is the oldest state park in the U.S.",
            "The Empire State Building was completed in 20 months.",
            "The International Boxing Hall of Fame is located in New York.",
            "The Statue of Liberty has a 35 foot waistline.",
            "The statue of Liberty weighs 450,000 pounds.",
            "The Statue of Liberty's name is Liberty Enlightening the World.",
            "Krispy Kreme Doughnuts was founded in North Carolina.",
            "The first gold rush was in North Carolina.",
            "Ohio is the only state whose flag isn't a rectangle.",
            "The world's largest cuckoo clock is in Sugarcreek, Ohio.",
            "Watermelon is the state vegetable of Oklahoma.",
            "Crate Lake in Oregon is America's deepest lake at over 1900 feet.",
            "Pennsylvania is misspelled on the Liberty Bell.",
            "Philadelphia was the second national capital.",
            "Philadelphia was the national capital for 10 year.",
            "The first high school driver's ed class in the U.S. took place in Pennsylvania.",
            "The first magazines in America were printed in Philadelphia.",
            "Rhode Island has the first baptist church in the U.S.",
            "Rhode Island has the oldest synagogue in the U.S.",
            "Rhode Island is the smallest U.S. state.",
            "Rhode Island's official name is State of Rhode Island and Providence Plantations.",
            "There was President of South Carolina.",
            "Jewel Cave in South Dakota is the third longest cave in the world.",
            "South Dakota is in 2 time zones.",
            "South Dakota is the only state whose name does not share a letter with its capital.",
            "There is a salt and pepper shaker museum in Tennessee.",
            "Braken Cave in Texas contains an estimated 20 million bats.",
            "Texas has 730 airports, the second most in the U.S.",
            "Texas has its own pledge of allegiance.",
            "The Bracken Cave in Texas contains the world's largest colony of bats.",
            "There is a Dr Pepper Museum in Texas.",
            "The Great Salt Lake is the largest saltwater lake in the Western Hemisphere.",
            "Vermont has one telephone area code.",
            "Vermont is the only state whose capital doesn't have a McDonald's.",
            "Vermont was its own country before becoming the 14th state.",
            "Vermont was originally named New Connecticut.",
            "Spokane, Washington is the smallest city to host a World's Fair.",
            "The Space Needle was built in 400 days.",
            "Charles Town, West Virginia is named after George Washington's brother.",
            "West Virginia has only one natural lake.",
            "West Virginia is the most mountainous state.",
            "The first kindergarten was created in Wisconsin.",
            "The Republican Party was created in Wisconsin.",
            "The majority of Yellowstone National Park is in Wyoming.",
            "Wyoming has the nation's largest hot spring.",
            "Wyoming was the first state to allow women voting.",
            // International Geography
            "Antarctica is the only continent without snakes.",
            "Antarctica is the world's largest desert.",
            "There is one insect native to Antarctica.",
            "Australia is a continent and a country.",
            "Australia's Highway 1 is the longest national highway in the world.",
            "Lake Hillier is a pink lake in Australia.",
            "Melbourne, Australia was briefly called Batmania.",
            "The Australian football team is nicknamed the Socceroos.",
            "There is a mountain in Australia called Mount Disappointment.",
            "Snake Island is an island in Brazil that is closed to the public due to snakes.",
            "The Bororo people of Brazil all have Type O blood.",
            "Canada is the 2nd largest country in size.",
            "License plates in northwest Canada are shaped like polar bears.",
            "The Mall of America is owned by Canadians.",
            "China owns all or nearly all pandas in the world.",
            "The Great Wall has other names such as The Long Wall.",
            "The Great Wall is a collection of walls.",
            "The Great Wall is not visible from space.",
            "The Great Wall took more than 1800 years to be built.",
            "The Great Wall was not great at keeping invaders out.",
            "In Croatia, on the coast is a sea organ that plays music using sea waves.",
            "Bacardi was founded in Cuba.",
            "Cuba is the largest island in the Caribbean.",
            "Cuba's national bird is the Cuban trogon.",
            "The world's largest underground waterfall is the known as the Denmark Strait cataract.",
            "Chimborazo is the farthest point on Earth's surface from the Earth's center.",
            "The Great Pyramid of Giza is the largest pyramid in Egypt.",
            "El Salvador is the smallest country in Central America.",
            "A woman married the Eiffel Tower.",
            "France gives medals to citizens who have successfully raised several children with dignity.",
            "France has the most time zones in the world.",
            "France introduced the license plate.",
            "France uses 12 different time zones.",
            "Louis XIX was King of France for 20 minutes.",
            "Paris was originally a roman city named Lutetia.",
            "The Eiffel Tower was inaugurated the same year Nintendo was founded.",
            "The Eiffel Tower was not intended to be permanent.",
            "The Eiffel Tower was once yellow.",
            "The Eiffel Tower was the world's tallest structure for 40 years.",
            "The Louvre museum started out as a fortress.",
            "The Louvre museum was temporarily named after Napoleon.",
            "The main bell in Notre Dame's Cathedral weighs 13 tons.",
            "There is only one stop sign in Paris.",
            "Chinese checkers was invented in Germany.",
            "The Berlin Wall was actually two walls.",
            "The Berlin Wall was more than 87 miles long.",
            "Iceland has no standing army.",
            "Iceland is free of mosquitoes.",
            "There are no McDonald's in Iceland.",
            "India's national animal is the Bengal Tiger.",
            "Indonesia contains more than 16,000 islands.",
            "Indonesia is the world's largest island country.",
            "The Komodo dragon is the national animal of Indonesia.",
            "There's a volcano in Indonesia that spews blue flames.",
            "Happy hour is banned in Ireland.",
            "There is a national Leprechaun Museum in Ireland.",
            "In some Israeli schools they use an upside T instead of a plus symbol.",
            "Israel drafts both men and woman for military service.",
            "The Hoopoe is the national bird of Israel.",
            "Galileo's finger is on display at a museum in Italy.",
            "The leaning tower of pisa began tilting during construction.",
            "There is a vineyard in Italy that has a 24/7 wine fountain that is free to use.",
            "Gambling is banned in Japan with the exception of horse and some motor sports.",
            "In Japan, farmers grows watermelons in shapes such as cube, pyramids, hearts and human faces.",
            "In Japan, stamps are used regularly instead of signatures.",
            "In Japan, there is a building with a highway that passes through it.",
            "Japan bases its calendar on the emperor.",
            "Japan has over 6,000 islands, about 430 are inhabited.",
            "Japanese stamp for signing is called Hanko.",
            "Nintendo was founded in 1889 and specialized in playing cards.",
            "The bluish looking traffic lights in Japan are green, it is just a very blue shade of green.",
            "Tokyo Disneyland is the first Disney park to be build outside the United States.",
            "Tokyo's original name was Edo.",
            "Lesotho is the only country that is entirely above 3281 feet.",
            "Mexico's official name is United Mexican States.",
            "The largest pyramid known to exist is in Mexico.",
            "The Xoloitzcuintle is the national dog of Mexico.",
            "New Zealand is part of a continent that has submerged.",
            "The Kiwi is the national animal of New Zealand.",
            "In Norway, advertising to children under 12 is illegal.",
            "There is a town in Norway called Hell.",
            "The Amazon River starts in Peru.",
            "Iquitos is the largest city in the world that cannot be reached by road.",
            "The world's tallest flowering plant Puya Raimondii grows in Peru.",
            "Beer was not classified as alcohol until 2013 in Russia.",
            "Russia is only around 2 miles from America.",
            "Scotland has approximately 790 islands, 130 are inhabited.",
            "The national animal of Scotland is the unicorn.",
            "The raincoat was created in Scotland.",
            "The shortest commercial flight is between to Scottish islands.",
            "The shortest commercial flight is under 2 miles.",
            "The shortest commercial flight takes on average a minute and half.",
            "Spain's official name is Kingdom of Spain.",
            "The bull is the national animal of Spain.",
            "The Spanish national anthem has no official lyrics.",
            "The Tower of Hercules in Spain is the oldest Roman lighthouse in use today.",
            "There is a tomato throwing festival in Spain called La Tomatina.",
            "Sudan has the most pyramids.",
            "Absolut Vodka was owned by the Sweden government.",
            "Swedish was announced as the official language of Sweden in 2009.",
            "The capital of Sweden, Stockholm is on 14 islands.",
            "Woman gained the right to vote in Switzerland in 1971.",
            "In the UK, horses, ponies and donkeys must have a passport.",
            "London's Big Ben refers to the bell inside the tower, not the tower.",
            "The tower Big Ben is located in, is named Elizabeth Tower.",
            "The UK is not required to name itself on stamps.",
            "Vatican City is the smallest country in the world.",
            // Cars
            "The inventor of cruise control was blind.",
            "The last new car to have a factory equipped cassette disk was a 2010 Lexus.",
            "Volkswagen owns Bentley, Bugatti, Lamborghini, Audi, Ducati and Porsche.",
            "Volvo gave away the patent for seatbelts for free to improve safety.",
            // Books
            "In the book, Dorothy from the wizard of Oz wore silver shoes.",
            "The book green eggs and ham contains only 50 different words.",
            "The book green eggs and ham was created through a bet between Dr. Seuss and his publisher.",
            // Famous People
            "Al Capone played banjo in the Alcatraz prison band.",
            "Alexander the Great never lost a battle.",
            "Before acting, Bruce Willis was a private investigator.",
            "Ben Franklin created the odometer.",
            "Ben Franklin is in the International Swimming Hall of Fame.",
            "Ben Franklin never patented any of his inventions.",
            "Ben Franklin was inducted into the Chess Hall of Fame.",
            "Ben Franklin was the first Postmaster General.",
            "Ben Franklin's son William was a British loyalist.",
            "Cleopatra was not Egyptian",
            "Columbus made 4 trips to the Americas.",
            "Elvis failed a music class in high school.",
            "Elvis never performed outside of North America.",
            "Fergie played the voice of Charlie Brown's sister Sally.",
            "Gandhi never won the Nobel Peace Prize.",
            "Houdini's brother was also a magician.",
            "Julius Caesar was once kidnapped by pirates.",
            "Nelson Mandela is an honorary Globetrotter.",
            "Orville Wright was the first to fly due to a coin toss that he lost.",
            "Queen Elizabeth II doesn't have a passport.",
            "Steve Carell worked as a postal carrier.",
            "The Harlem Globetrotters have a star in the Hollywood Walk of Fame.",
            "The Wright brothers flew together only once.",
            "Walt Disney joined the Red Cross as a teenager.",
            "Walt Disney was the voice of Mickey Mouse.",
            "Walt Disney worked as a post office worker.",
            "Winston Churchill escaped a South Africa prison camp.",
            "Winston Churchill was an award-winning author.",
            // Fears
            "Ailurophobia is the fear of cat.",
            "Anatidaephobia is the fear that somewhere, somehow a duck is watching you.",
            "Anthonphobia is the fear of flowers.",
            "Arithmophobia is the fear of numbers.",
            "Aulophbia is the fear of flutes.",
            "Aurophobia is the fear of gold.",
            "Bibliophobia is the fear of books.",
            "Consecotaleophobia is the fear of chopsticks.",
            "Coulrophobia is the fear of clown.",
            "Equinophobia is the fear of horses.",
            "Hylophobia is the fear of forests.",
            "Linonophobia is the fear of string.",
            "Nomophobia is the fear of being without your phone or being unable to use it.",
            "Ombrophobia is the fear of rain.",
            "Ommatophobia is the fear of eyes.",
            "Ophidiophobia is the fear of snakes.",
            "Papaphobia is the fear of the Pope.",
            "Phobophobia is the fear of phobias.",
            "Pogonophobia is the fear of beard.",
            "Porphyrophobia is the fear of purple.",
            "Selenophobia is the fear of the moon.",
            "Somniphobia is the fear of falling asleep.",
            "Turophobia is the fear of cheese.",
            "Ttypophobia is the fear of small holes.",
            "Xanthophobia is the fear of the color yellow.",
            // Govt, History, Military
            "During the Civil War there was a Union Army Balloon Corps.",
            "GPS is owned by the US government.",
            "Hundreds of women disguised as men and fought in the Civil war.",
            "Only one justice has been impeached from the Supreme Court.",
            "Only one woman has been awarded the Army Medal of Honor.",
            "Supreme Court justices are appointed for life.",
            "The 50 Star American flag was designed by a high school student.",
            "The American flag's colors are white, old glory red and old glory blue.",
            "The Hundred Years' War lasted 116 years.",
            "The Marine Band is nicknamed 'The President's Own'.",
            "The Marine Corps is part of the Dept. of the Navy.",
            "The Seven Years' War lasted nine years.",
            "The U.S. navy has one ship on its commissioned roster being held captive by North Korea.",
            "The U.S. navy has trained dolphins.",
            "The U.S. navy has trained sea lions.",
            "There are no qualifications for becoming a Supreme Court Justice.",
            "There is a basketball court above the Supreme Court.",
            // Inventions
            "Earmuffs were created by a 15 year old.",
            "Parachute was created before airplane.",
            "The electric chair was created by a dentist.",
            "The shopping cart was created in Oklahoma.",
            // Money
            "Andrew Jackson has been on the $20 bill since 1929.",
            "Ben Franklin has been on the $100 bill for over 100 years.",
            "Bills larger and $100 are no longer printed.",
            "The clock on the back of the new $100 bills shows the time 10:30.",
            "U.S. money is composed of 75% cotton and 25% linen.",
            // Movies & TV
            "Movie trailers originally came after movies.",
            "Titanic was the first movie to be sold for home watching while still in theatres.",
            "Titanic was the first movie to reach the billion dollar mark.",
            "The budget for Paranormal activity was $15,000, it made $193 million in box office.",
            "The 1st music video on MTV was Video Killed the Radio Star.",
            "The movie Rocky was shot in 28 days.",
            "The opening credits for the show Friends were shot at Warner Bros. studio.",
            "Thomas Edison built the first movie studio.",
            // Music
            "An earworm is a song that continuously plays in your mind after it is no longer playing.",
            "Frank Sinatra never learned to read music.",
            "Jimi Hendrix never learned to read music.",
            "Pianos can have over 12,000 parts.",
            "The band Queen was originally called Smile.",
            "The Beatles never learned to read music.",
            // Olympics
            "Denver won the 1970 Olympics then later withdrew.",
            "Figure skating and ice hockey were originally in the Summer Olympics.",
            "Only one country has ever boycotted the Winter Olympics.",
            "Solid gold medals were last used for Olympics in 1912.",
            "Two separate U.S. men's hockey teams arrived at the 1948 Winter Olympics.",
            // Presidents
            "Abraham Lincoln created the secret service.",
            "Abraham Lincoln is in the Wrestling Hall of Fame.",
            "Abraham Lincoln is the only president to get a patent.",
            "Abraham Lincoln was the first president born in the 19th century.",
            "Abraham Lincoln worked as a postmaster.",
            "Andrew Jackson hated banks, he shut down the second bank of the U.S.",
            "Andrew Jackson was the only president to have been a prisoner of war.",
            "Barack Obama is the first president from Hawaii.",
            "Barack Obama is the first president to visit a federal prison while in office.",
            "George Washington is the only president to not represent a political party.",
            "George Washington is the only President to receive 100% electoral votes.",
            "George Washington's second inaugural address was the shortest ever.",
            "Herbert Hoover was the first president born west of the Mississippi River.",
            "John Adams wrote the oldest constitution that is still in use today.",
            "John Adams was the first president to live in the White House.",
            "John F Kennedy was the first president born in the 20th century.",
            "John F Kennedy was the first president to be a Boy Scout.",
            "Martin Van Buren was the first president born after the American Revolution.",
            "Richard Nixon could play 5 musical instruments.",
            "Richard Nixon was an avid bowler.",
            "The painting of George Washington that was used for the dollar was never finished.",
            "Theodore Roosevelt had a pet hyena named Bill.",
            "Theodore Roosevelt was a New York City police commissioner.",
            "Theodore Roosevelt was the first president to leave the U.S.",
            "William Howard Taft is the only person to serve as president and Supreme Court justice.",
            // Thing Names
            "A person who steals books is a biblioklept.",
            "An ambivert is a person who displays qualities of an extrovert and introvert.",
            "An eye exam chart is called a snellen chart.",
            "Aglets are the small tube at the end of a shoelace.",
            "Ambisinistrous is the opposite of ambidextrous.",
            "Barm is the foam on a beer.",
            "Eating horseflesh is called hippophagy.",
            "Illegible handwriting is called griffonage.",
            "Morton's toe is when your second toe is bigger than your big toe.",
            "Nearsighted is called Myopia.",
            "Sphenopalatine ganglioneuralgia is the scientific term for brain freeze.",
            "Tartle is the scottish word for hesitating when you can't remember someone's name.",
            "The cardboard sleeve used for coffee or hot beverages is called a zarf.",
            "The dot in i/j us called a tittle.",
            "The dots on dice or shapes on a playing card are called pips.",
            "The indent on the bottom of a wine bottle is called a punt.",
            "The medical condition for runny nose is rhinorrhea.",
            "The metal piece that holds eraser and pencils together is called a ferrule.",
            "The pins and needles feeling is call paresthesia.",
            "The technical term for #, is octothorpe.",
            "The wattle is the red thing that hangs under a turkey's chin.",
            "The wire cage that keeps the cork on in a bottle of champagne is called an agraffe.",
            "Twitter's bird is named Larry.",
            "Zip Code is an acronym for Zone Improvement Plan.",
            // Other
            "2520 can be divided by all numbers from 1 to 10.",
            "America's first steam locomotive lost a race to a horse.",
            "Big Ben and the Liberty Bell were cast by the same company, both cracked.",
            "Bluetooth is named after a Denmark king.",
            "Cacao was once used as currency by the Aztecs.",
            "Cocoa and cacao are the same thing.",
            "Gold has been found on every continent.",
            "Google owns the website googlesucks.com",
            "Google used a camel for street view of a desert.",
            "Google's headquarters is called the Googleplex.",
            "Jerry Springer was once mayor of Cincinnati.",
            "Jessica Cox is the world's first licensed armless pilot.",
            "Left Handers Day is August 13th.",
            "National Watermelon Day is August 3rd.",
            "Opposite sides of a dice add up to 7.",
            "Over 2200 years ago, Eratoshenes calculated the Earth's circumference.",
            "Over 2200 years ago, Eratoshenes calculated the Earth's tilt.",
            "Picasso paintings have been stolen more than any other artists.",
            "September is the only length of letters equals its month number.",
            "Superman was first envisioned as a villain.",
            "The average cloud weighs 1.1 million pounds.",
            "The creator of the peanuts comic didn't like the name.",
            "The Oregon Trail didn't follow a single set path.",
            "The Q in Q-tips stands for quality.",
            "The word queue is pronounced the same when the last 4 letters are removed.",
            "The World Series has been cancelled twice.",
            "There is a museum devoted to Peanuts the comic.",
            "There was a chimp named Congo who learned how to draw and paint.",
            "Trees sleep at night.",
            "Typewriter can be written using only the top row of a standard keyboard.",
            "Viking men wore makeup.",
            "Vikings skied for fun and travel.",
            "Volcano surfing is an extreme sport.",
            "You can swim through syrup just as fast as you can swim through water.",
    };

    // Methods = Actions the object can take
    String getFact() {
        // Randomly select a fact
        int randomNumber = randomGenerator.nextInt(facts.length);
        return facts[randomNumber];
    }
}
